# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77c6987edc0e36e40a10c63c6cd9eefa506fe823aaf0ad63950d8fb322c525772c3d069d1123e7a7060cd2a3d178d82f92087220c43d7b1c79f7c30ab3972267

test:
  secret_key_base: 78b5b6cf8330a759d81a99ea3732a8e9c8b973210a2b7a710b9b5f4e3146261ff44a1dd4c82438cd81773ea972c05ec089dd07ec3f74f35ad0a397c8f434173a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
